import netlify from "@netlify/vite-plugin-tanstack-start";
import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";

// Plugin order is load-bearing: tailwindcss() before tanstackStart(),
// tanstackStart() before viteReact(). See TanStack Start's Vite plugin
// ordering docs — getting this wrong fails at build time, not runtime.
//
// netlify() adapts tanstackStart()'s output, and emulates Netlify's
// production platform in local dev (functions, redirects, headers, env), so
// `pnpm dev` matches production rather than approximating it.
//
// There is deliberately no vite-plugin-pwa here. TanStack Start runs two Vite
// build environments; the plugin emitted its manifest into both and generated
// no service worker at all, and pinning it to the client environment then
// broke the server build's resolution of `virtual:pwa-register`. The worker is
// generated by `scripts/generate-sw.mjs` after the build instead, which is
// deterministic and independent of how many environments Vite runs. The web
// manifest is a static asset in `public/`.
export default defineConfig({
  server: {
    port: 3000,
  },
  // Vite does not read tsconfig `paths`, so the "@/*" alias has to be
  // declared here as well as in tsconfig.json (which only informs tsc and
  // the editor). vitest.config.ts needs its own copy for the same reason.
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  plugins: [
    tailwindcss(),
    tanstackStart({
      // Prerenders one generic, data-free HTML document at build time
      // (`dist/client/_shell.html`) — TanStack Start's own SPA-shell feature
      // (`router.update({ isShell: true })` skips every loader, so the
      // output carries no route-specific data and is safe to boot against
      // any URL). `generate-sw.mjs` precaches it as the offline navigation
      // fallback (plan finding 1): the server-rendered response is always
      // preferred online, and this is only what a hard-reload offline falls
      // back to when the network can't be reached at all.
      spa: { enabled: true },
    }),
    netlify(),
    viteReact(),
  ],
});
