/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as cmsBlogRouteRouteImport } from './routes/(cms)/blog/route'
import { Route as cmsHelpRouteImport } from './routes/(cms)/help'
import { Route as cmsReleasesRouteImport } from './routes/(cms)/releases'
import { Route as cmsBlogIndexRouteImport } from './routes/(cms)/blog/index'
import { Route as cmsBlogSlugRouteImport } from './routes/(cms)/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const cmsBlogRouteRoute = cmsBlogRouteRouteImport.update({
  id: '/(cms)/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const cmsHelpRoute = cmsHelpRouteImport.update({
  id: '/(cms)/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const cmsReleasesRoute = cmsReleasesRouteImport.update({
  id: '/(cms)/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const cmsBlogIndexRoute = cmsBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => cmsBlogRouteRoute,
} as any)
const cmsBlogSlugRoute = cmsBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => cmsBlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/blog': typeof cmsBlogRouteRouteWithChildren
  '/help': typeof cmsHelpRoute
  '/releases': typeof cmsReleasesRoute
  '/blog/$slug': typeof cmsBlogSlugRoute
  '/blog/': typeof cmsBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/help': typeof cmsHelpRoute
  '/releases': typeof cmsReleasesRoute
  '/blog/$slug': typeof cmsBlogSlugRoute
  '/blog': typeof cmsBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/(cms)/blog': typeof cmsBlogRouteRouteWithChildren
  '/(cms)/help': typeof cmsHelpRoute
  '/(cms)/releases': typeof cmsReleasesRoute
  '/(cms)/blog/$slug': typeof cmsBlogSlugRoute
  '/(cms)/blog/': typeof cmsBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/blog'
    | '/help'
    | '/releases'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/admin' | '/help' | '/releases' | '/blog/$slug' | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/(cms)/blog'
    | '/(cms)/help'
    | '/(cms)/releases'
    | '/(cms)/blog/$slug'
    | '/(cms)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  cmsBlogRouteRoute: typeof cmsBlogRouteRouteWithChildren
  cmsHelpRoute: typeof cmsHelpRoute
  cmsReleasesRoute: typeof cmsReleasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cms)/blog': {
      id: '/(cms)/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof cmsBlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cms)/help': {
      id: '/(cms)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof cmsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cms)/releases': {
      id: '/(cms)/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof cmsReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(cms)/blog/': {
      id: '/(cms)/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof cmsBlogIndexRouteImport
      parentRoute: typeof cmsBlogRouteRoute
    }
    '/(cms)/blog/$slug': {
      id: '/(cms)/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof cmsBlogSlugRouteImport
      parentRoute: typeof cmsBlogRouteRoute
    }
  }
}

interface cmsBlogRouteRouteChildren {
  cmsBlogSlugRoute: typeof cmsBlogSlugRoute
  cmsBlogIndexRoute: typeof cmsBlogIndexRoute
}

const cmsBlogRouteRouteChildren: cmsBlogRouteRouteChildren = {
  cmsBlogSlugRoute: cmsBlogSlugRoute,
  cmsBlogIndexRoute: cmsBlogIndexRoute,
}

const cmsBlogRouteRouteWithChildren = cmsBlogRouteRoute._addFileChildren(
  cmsBlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  cmsBlogRouteRoute: cmsBlogRouteRouteWithChildren,
  cmsHelpRoute: cmsHelpRoute,
  cmsReleasesRoute: cmsReleasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
